config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: [:index, :show]
  resources :users, only: [:show, :destroy]
  resources :recipes, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user 
    belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :allergies
    has_many :users, through: :allergies 

    def self.sorted_by_allergies
        self.all.sort_by do |ingredient|
            ingredient.allergies.size
        end.reverse
    end 


        #self.all.sort_by(ingredient.user.size) ?


    
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    belongs_to :user 

    def self.sorted_by_ingredients 
        self.all.sort_by do |recipe|
            recipe.ingredients.size
        end.reverse 
    end 
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe 
    belongs_to :ingredient 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :allergies 
    has_many :ingredients, through: :allergies 
    has_many :recipes

    def destroy_recipes 
        self.recipes.each do |recipe|
            recipe.destroy 
        end 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index 
        @ingredients = Ingredient.sorted_by_allergies 
    end 

    def show 
        @ingredient = Ingredient.find(params[:id])
    end 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index 
        if params[:sorted] == "true"
            @recipe_type = "Sorted"
            @recipes = Recipe.sorted_by_ingredients 
        else 
            @recipes = Recipe.all
        #sort? if yes do below 
        end 
        render(:index)
    end 

    def show 
        @recipe = Recipe.find(params[:id])
    end 

    def new 
        @recipe = Recipe.new
    end 

    def create 
        recipe = Recipe.create(name: recipe_params(:name))
        user = User.find_or_create_by(name: recipe_params(:user))
        recipe.update(user: user)
        redirect_to recipe_path(recipe)
    end 

    private

    def recipe_params(*args)
        params.require(:recipe).permit(*args)
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show 
        @user = User.find(params[:id])
    end 

    def destroy 
        user = User.find(params[:id])
        user.destroy_recipes 
        user.destroy
        redirect_to recipes_path
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1> Ingredients Ordered by Number of Allergies </h1>
<ul>
    <% @ingredients.each do |ingredient|  %>
    <li>
    <%= ingredient.name  %> - <%= ingredient.allergies.size %>
    </li>
    <% end %> 
</ul>

app/views/ingredients/show.html.erb
<h1> Ingredient </h1>
<h1> <%= @ingredient.name%> </h1>
<h1> Recipes with Ingredient </h1>

<ul>
    <% @ingredient.recipes.each do |recipe| %> 
        <li>
        <%= recipe.name %> 
        <li>
    <% end %> 
 <ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= form_tag recipes_path, method: "GET" do %>
    <%= label_tag "Sort" %>
    <%= radio_button_tag "sorted", 'true' %>
    <%= label_tag "Not Sorted" %>
    <%= radio_button_tag "sorted", 'false' %>
    <%= submit_tag %>
<% end %>

<ul>
    <% @recipes.each do |recipe|  %>
    <li>
    <%= link_to recipe.name, recipe_path(recipe.id) %> - <%= recipe.ingredients.size %>
    </li>
    <% end %> 
</ul>


<%= button_to "New Recipe", new_recipe_path, method: "get"  %>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :name, "Recipe Name" %>
    <%= f.text_field :name %>
    <%= f.label :user, "Author" %>
    <%= f.text_field :user %>
    <%= f.submit "New Recipe" %>
<% end %>

app/views/recipes/show.html.erb
<h1> Recipe </h1>
<h1> <%= @recipe.name%> </h1>


<ul>
    <% @recipe.ingredients.each do |ingredient| %> 
        <li>
        <%= ingredient.name %> 
        </li>
    <% end %> 
 <ul>

app/views/users/show.html.erb
<h1> User Name </h1>
<h1> <%= @user.name%> </h1>
<h1> User Recipes </h1>

<ul>
    <% @user.recipes.each do |recipe| %> 
        <li>
        <%= recipe.name %> 
        <li>
    <%end%>
 <ul>